### ISSUE TITLE
stepper.setAcceleration на разных stepper.setMaxSpeed живет своей непонятной и загадочной жизнью

### ISSUE THREAD

**Issue by Brandvik** [GyverLibs/GyverStepper#14]
Всем здравствуйте. 
Библиотека 2.6.4
328Р
Загружаем пример из Stepper2 - StepperControl 
задаем 
stepper.setAcceleration (100000)  // на 100 000 особенно почему-то все ломается , на 50 000 и ниже, работает сносно и хорошо
 stepper.setMaxSpeed (5000)          //  а так же 10000, 15000 и 20000
 
int16_t path[] = {0, 16000};   

Пробуем в плоттере (в жизни все так же) остановить ,функцией  stepper.stop()  (S), мотор на разных этапах движения... 
Наслаждаемся странным поведеним торможения
Ускорение после 50 000  быстрее не становистя, с делителем 16 очень грустно все разгоняется...
Потом попробуйте ввести 
stepper.setAcceleration (200000)
Получаем по факту как будто ввели 2000... 
 В общем что это все, баг или фича ?

**Comment by GyverLibs** [comment]
Чувствую что с такими огромными числами происходит переполнение 32 бит при вычислениях

**Comment by GyverLibs** [comment]
> Ускорение после 50 000 быстрее не становистя

Стоило бы с документацией ознакомиться
```cpp
void setAcceleration(uint16_t acc);
```

**Comment by Brandvik** [comment]
От я "Маша"!  И ведь читал-перечитывал прежде чем ту написать. А на тип данных не обратил внимание.... Так с этим разобрался. 
Но можно ли как-то увеличить ускорение разгона торможения? Как я уже говорил, при работе с делителем 16 ускорение может и должно быть быстрее, а то кокой то вялый огурец получается
И остается вопрос, почему торможение при вызове функции стоп происходит медленнее чем разгон\торможене при штатной работе функции  setTarget ? Особенно это заметно когда стоп вызван чуть раньше чем начинается "штатное" замедление, скорость падает и мотор доходит до заданного значения, а скорость еще не 0 и происходит резкая остановка. Вроде шаги не теряются, все таки скорость близка к нулю, но как то "не приятно" слышать "удар".

**Comment by GyverLibs** [comment]
> можно ли как-то увеличить ускорение разгона торможения?

попробую в следующий раз как буду ковырять библиотеку

> торможение при вызове функции стоп происходит медленнее чем разгон\торможене

на каких настройках скорости/ускорения? Работа через прерывания или просто в лупе?

**Comment by Brandvik** [comment]
`на каких настройках скорости/ускорения? Работа через прерывания или просто в лупе?`

 работа в лупе, но по сути голый тэстовый скетч опрос двух ног для кнопок да асинх. вывод позиции в терминал 
stepper.setAcceleration(50000);
  stepper.setMaxSpeed(20000);

Выглядит так

![изображение](https://user-images.githubusercontent.com/36903102/208251793-08eff2fd-956e-48d1-80d6-12f49e276106.png)

А вот "ударная" остановка
![изображение](https://user-images.githubusercontent.com/36903102/208252097-32b1f281-1799-4afe-ab15-4614bb088d8e.png)

На скорости 10000 это тоже все проявляется

Со снижением ускорения в два раза эффект не проявляется или просто на глаз становится не заметен...

**Comment by GyverLibs** [comment]
записал себе. Где то в вычислениях траектории возможно что то переполняется и считается неправильно

**Comment by Brandvik** [comment]
Не знаю, актуально ли будет, но вот еще информация, может окажется полезной.
Завел на прерывания и получил такую картину, после полного разгона по функции стоп  торможение срабатывает строго через раз в любом месте траектории...
 
![изображение](https://user-images.githubusercontent.com/36903102/208320369-5cdd9cfd-ef8a-4d8d-86c9-ffcb37da539a.png)

Когда тикало в лупе такого эффекта не наблюдалось.
ЗЫ Если не в лом. ткните носом почему на таймерах это работает

```
stepper.setTarget (6400);
  setPeriod(stepper.getPeriod());
    startTimer();
```
  а это не работает   
```
 stepper.setSpeed(-10);
    setPeriod(stepper.getPeriod());
    startTimer();
```

 и вобще не работает setSpeed если НЕ тикать в лупе?

А если завести таймер и тикать в лупе то скорости setTarget  в два раза вырастают :) Но это вопрос риторический...

**Comment by GyverLibs** [comment]
Вот тут видимо нужно добавлять volatile. Странно что раньше не всплыло, я очень плотно тестировал и с прерываниями и без

**Comment by GyverLibs** [comment]
В текущем обновлении нашел и исправил проблему со слишком медленной остановкой при высоких ускорениях
