### ISSUE TITLE
esphome совместимость

### ISSUE THREAD

**Issue by iqubik** [GyverLibs/GyverStepper#21]
Алекс, привет.
Делаю сейчас проект жалюзи на esphome для системы умного дома home assistant.
Очень хочу попросить рассмотреть возможность сделать библиотеку совместимой с esphome.
Дело в том что встроенная библиотека шаговика на esphome сделана просто ужасающе - она дергается, у неё минимум функционала и она чрезвычайно устарела.
Сам esphome можно установить отдельно от home assistant используя команды отсюда 
https://esphome.io/guides/installing_esphome.html
И запускать чем то вроде ярлыка ..\AppData\Local\Programs\Python\Python312\Scripts\esphome.exe ..\config\ dashboard

**Comment by GyverLibs** [comment]
привет, gyverstepper работает в среде ардуино и со всем совместим
