### ISSUE TITLE
esp32 нет генерации шагов

### ISSUE THREAD

**Issue by iqubik** [GyverLibs/GyverStepper#25]
У меня на esp32 gyverStepper вообще не генерирует импульсы на любых примерах из либы.
Конкретно пробовал пины для step 22 и 5. 2wire step dir config
При этом dir стабильно меняет положение соответственно текущему шагу из базового примера например.
Смотрю осциллографом - на step импульсов не завезли, а dir работает.

**Comment by GyverLibs** [comment]
всё отлично работает, проверяйте  пины/подключение/скетч

**Comment by iqubik** [comment]
Полностью переустановил arduino ide  на свежайшую 2.3.4 обновил все либы и компоненты.
Версия gyverSteeper крайняя 2.7.0
В качестве платы выбираю esp32 по тегу dev.

Взял sweep пример и залил на классическое esp32 вообще без изменения кода скетча на 2 esp32 с использованием крайнего ядра espressif 3.1.0.
Осциллограф - нет генерации step. Консоль - алгоритм работает и считает шаги меняя направления.
Dirpin меняет направление.

Меняю в примере пины dir и step местами и пин который не генерировал step успешно работает с dir, а пин который ранее успешно работал с dir не создаёт импульсов для step.
ЧЯДНТ?)

Ставлю сейчас ядро версии 3.0.0

**Comment by iqubik** [comment]
Ядро версии 3.0.0 есть генерация! На крайнем ядре 3.1.0 либа не даёт генерации
Ставлю предкрайнее 3.0.7 для проверки

3.0.7 - так же нет генерации. Ставлю крайнее из 2 ветки 2.0.17
2.0.17 - не обнаружил генерации

3.1.0 заработала после переустановки ide
