### ISSUE TITLE
Kernel panic Speed=0

### ISSUE THREAD

**Issue by iqubik** [GyverLibs/GyverStepper#7]
На esp32 если вызвать функцию конструкцию типа:
  stepper.setMaxSpeed(0);     // скорость движения к цели
  stepper.setAcceleration(0); // ускорение
  stepper.setTarget(10000);       // цель
Получаем kernel panic и постоянную перезагрузку контроллера.
Можно ли сделать обработчик такого неверного запуска движения, который будет просто говорить Готово?
Спасибо!

**Comment by GyverLibs** [comment]
Это stepper или stepped 2?

**Comment by iqubik** [comment]
> Это stepper или stepped 2?
Stepper2

**Comment by GyverLibs** [comment]
Пока не нашел причин для паники, но в ближайшем обновлении постараюсь поправить

**Comment by GyverLibs** [comment]
не смог понять что не понравилось kernel'у, при задании нулевой скорости там сразу выход из функции без применения этой скорости, и скорость остаётся прежней. Сейчас сделал, чтобы задание нулевой скорости вообще не позволяло запустить setTarget. Жду тестов

**Comment by GyverLibs** [comment]
Да, пофиксилось
