### ISSUE TITLE
Чуть больше документации к коду

### ISSUE THREAD

**Issue by zag2art** [GyverLibs/GyverStepper#8]
Изучаю код планеров. Функции вполне нормально документированы, но чуток не хватает описания приватных полей. Приходится по всему коду бегать, чтобы собрать, что за что отвечает. Спасибо за модуль.

**Comment by GyverLibs** [comment]
Приватных? Расписать за что отвечают приватные переменные?

**Comment by zag2art** [comment]
Да, если не трудно. Разбираюсь как это все работает.

**Comment by GyverLibs** [comment]
Не знаю насколько это поможет, я уже сам наверное с трудом разберусь как оно работает) очень сжатые пережатые алгоритмы

**Comment by zag2art** [comment]
меня в основном планеры интересуют. сравниваю с тем как это сделано в grbl

**Comment by GyverLibs** [comment]
А есть где почитать по grbl? Я в свое время не смог разобраться и решил что проще написать с нуля свой планнер

**Comment by zag2art** [comment]
почитать я не нашел, но есть исходинки с самой первой версии. Вот, например, версия [0.1](https://github.com/grbl/grbl/commit/9df29ad3b3fb769317d9c5560c54e89c92a71680), я же смотрю версию [0.6](https://github.com/grbl/grbl/tree/v0_6) - последнюю, которую норвежец писал, там вроде и функционал уже основной и по структуре все устоялось. Есть комменты, плюс эта версия еще не такая большая, чтобы совсем запутаться.

Судя по всему в grbl похожий подход. Тоже строят трапеции по скорости, стараются несколько трапеций плавно соединить, чтобы избежать рывков, ну и интервалы между степами контролят по таймеру через прерывания (у вас tick-и, но это легко переделывается).

**Comment by zag2art** [comment]
https://awesome.tech/grbl-demystified/
https://openbuilds.com/threads/ask-grbl-cnc-questions-here.3000/
Вот все, что нашел по докам

**Comment by GyverLibs** [comment]
У меня тики как раз чтобы тикать в прерывании таймера :) Просто это полностью вынесено в скетч, чтобы можно было завести на любой платформе, там есть для примера как на 328 Меге работать с таймером.

У грбл используется brezenham? Я не придумал как сделать лучше, но с ним все остальные моторы (кроме нулевого) движутся неравномерно и вибрируют больше чем нужно

**Comment by zag2art** [comment]
> У меня тики как раз чтобы тикать в прерывании таймера :) Просто это полностью вынесено в скетч, чтобы можно было завести на любой платформе, там есть для примера как на 328 Меге работать с таймером.

Все верно, нужно абстрагироваться от железа. Если бы в grbl использовали этот же подход - код был бы во много раз проще. Там же все в кучу намешано.

> У грбл используется brezenham? Я не придумал как сделать лучше, но с ним все остальные моторы (кроме нулевого) движутся неравномерно и вибрируют больше чем нужно

Разбираюсь с этим. Как минимум, при рисовании линий в grbl они тоже находят ось, по которой дельта максимальна и смотрят сколько это степов. Именно это число и будет step_event_count - то есть числом эвентов, по которым будут толкаться степперы. Так что похоже, что без Брезенхема тут никак.

> движутся неравномерно и вибрируют больше чем нужно

вибрация и на тихих драйверах с внутренними микрошагами типа TMC2208 тоже чувствуется?

UPD - по видимому step_event_count еще детализируется. то-есть на каждый "эвент" еще и сколько-то "тиков" делается. Судя по [этому](https://github.com/grbl/grbl/blob/74576a8a0c1f3065a31f48c6e8515867423713e8/stepper.c#L61)

**Comment by zag2art** [comment]
Нашел, кстати по Брезенхему и как они борются с вибрацией - https://github.com/grbl/grbl/blob/master/grbl/stepper.c#L233 

Хитрые, они просто удваивают (либо умножают на 4 или  8) количество шагов в алгоритме Брезенхема, так что пульс основного двигателя остается тем же, а пульсы вспомогательных движков, возможно, уходят на доп. тики.

Считается, что проблема именно в том, что мы дергаем несколько движков в один и тот же момент. Если время чуток разнести, то вибрация уменьшается.

Еще судя по всему алгоритм у них адаптивный. когда скорость низкая, то на 8 частей делят. При высокой на 2. Как-то так.

**Comment by GyverLibs** [comment]
прикольно, надо над этим подумать! Но вибрации там не из за этого, а из за того, что мотор не имеет постоянной скорости. Основной мотор шагает с чётким периодом, а вот остальные могут делать условно два шага через шаг, то есть "шаг-шаг-пропуск-шаг-шаг-пропуск..." и в таком роде. Если увеличить разрешение - походу можно этого избежать, надо попробовать в симуляторе. По сути нужно домножить (сдвинуть) оффсеты осей для брезенхема, и доделить время таймера us, я думаю в зависимости от usMin

**Comment by zag2art** [comment]
Да, похоже, что с увеличением разрешения можно сделать пульсы второстепенных моторов более равномерными. Вместо "110110" будет что-то типа "100100100100" - соответственно и звук будет больше на синусоиду похож. И линии, кстати, будут плавнее и точнее.

**Comment by GyverLibs** [comment]
Ух попробую как будет минутка)

**Comment by GyverLibs** [comment]
если интересно, вот так у меня реализован брезенхем, код можно запустить в Processing. Тут на 2 оси, названия переменных +- такие же как в гуверпланере
```cpp
int scale = 5;
int dS[] = {0, 0};
int tar[] = {0, 0};
int pos[] = {0, 0};
int nd[] = {0, 0};
int steps[] = {0, 0};
int dir[] = {0, 0};
int S, maxAx, step;

void setup() {
  size(800, 800);
  noStroke();
  fill(0);
}

void draw() {
  background(255);
  tar[0] = mouseX / scale;
  tar[1] = mouseY / scale;
  pos[0] = width / 2 / scale;
  pos[1] = height / 2 / scale;
  steps[0] = pos[0];
  steps[1] = pos[1];
  
  S = 0;
  for (int i = 0; i < 2; i++) {
    dS[i] = abs(tar[i] - pos[i]);
    dir[i] = pos[i] < tar[i] ? 1 : -1;
    if (dS[i] > S) {
      S = dS[i];
      maxAx = i;
    }
  }
  for (int i = 0; i < 2; i++) nd[i] = S / 2;
  step = 0;


  while (step < S) {
    step++;
    square(steps[0] * scale, steps[1] * scale, scale);
    for (int i = 0; i < 2; i++) {
      if (i == maxAx) steps[i] += dir[i];
      else {
        nd[i] -= dS[i];
        if (nd[i] < 0) {
          nd[i] += S;
          steps[i] += dir[i];
        }
      }
    }
  }
}
```

Причём сейчас понял, что сам цикл движения можно упростить, выкинув персональное движение главного шаговика
```cpp
  while (step < S) {
    step++;
    square(steps[0] * scale, steps[1] * scale, scale);
    for (int i = 0; i < 2; i++) {
      nd[i] -= dS[i];
      if (nd[i] < 0) {
        nd[i] += S;
        steps[i] += dir[i];
      }
    }
  }
```

**Comment by GyverLibs** [comment]
собственно осталось домножить переменную брезенхема и общее расстояние на множитель, и получить дробные шаги!    
[brez2.zip](https://github.com/GyverLibs/GyverStepper/files/8017254/brez2.zip)
```cpp
  for (int i = 0; i < 2; i++) nd[i] *= mult;  
  S *= mult;
```
![brez](https://user-images.githubusercontent.com/84599917/152836983-ed879f6b-63ff-4ffa-a4b3-539ebec8be4d.png)

**Comment by zag2art** [comment]
Красота, видно, что оба движка толкаются равномерно. Как я понимаю, это при делении на 4 шага. Адаптивный вариант будет посложнее. Но если железо держит - вариант отличный.

В принципе можно попробовать сразу 4 варианта mult вести одновременно (1,2,4,8) решая на ходу какой из вариантов применить на очередном step-event-е. Если скорость маленькая - 8, максимальная - 1. Но это так - мысли вслух.

**Comment by zag2art** [comment]
Поставил себе processing - удобная штука, надо будет ваши видео по нему глянуть.

**Comment by GyverLibs** [comment]
Адаптивный - просто выбирать делитель в зависимости от времени usMin, и всё. Прикинуть, какая частота будет критической и не превышать её. Осталось придумать, как работать с повышенным разрешением брезенхема в условиях планировщика, возможно нужно пропускать n шагов для пересчёта времени. Там надо подумать, как нибудь на неделе займусь

**Comment by zag2art** [comment]
Будете дорабатывать, добавьте, плиз, чуток комментов к приватным переменным.

**Comment by zag2art** [comment]
Кстати, даже если mult будет равен 8, то реальных тиков все-равно будет максимум 3 - по количеству моторчиков. Один основной, который по главной оси, и от 0 до 2-х доп тиков для второстепенных. Получается, какой бы mult не был (хоть 32, хоть 64)- это просто точность повышает timestamp-а тиков дополнительных степперов. количество же событий не увеличивается.

**Comment by AlexGyver** [comment]
именно поэтому нужно делать "псевдотикер" внутри основного с пропуском sub-шагов

**Comment by GyverLibs** [comment]
Так, доделал ролик на завтра, сел попробовать степпер. Заработало сразу, вот до и после
![test (2)](https://user-images.githubusercontent.com/84599917/153284139-2e1e23f2-7179-4055-a38f-02f9d40dc6d5.png)
![test (1)](https://user-images.githubusercontent.com/84599917/153284148-23187ba4-ef9a-499a-a050-5ee1aa94fce6.png)

**Comment by zag2art** [comment]
И как звук с вибрациями? Стало лучше?

**Comment by GyverLibs** [comment]
Да, гораздо лучше

**Comment by zag2art** [comment]
За комменты в планере отдельное спасибо. Буду разбираться как вы s1 и s2 в трапециях вычисляете.

**Comment by GyverLibs** [comment]
Там всё из уравнения движения школьного. Я бы скинул выкладки по графикам и уравнениям, но оно всё вперемешку на листочках, я уже не помню на каком правильный вариант финальный)

**Comment by zag2art** [comment]
Я уже понял, что это о равноускоренном движении. [тут](https://physics.ru/courses/op25part1/content/chapter1/section/paragraph4/theory.html#.YgVjYO5Bz-Q), вроде, все есть. Интересно, что такие трапеции с равноускоренным движением - лишь один из видов профилей скоростей, которые в чпу применяются. Используя кривые второго порядка, старт и остановку моторов сглаживают. Типа это самые тяжелые моменты для станков. Еще есть какие-то "кинематические" профили - даже не знаю что это такое, но где-то читал, что это самое модно сейчас :) Вот [тут](https://docplayer.com/25851192-Sosonkin-v-l-martinov-g-m-metodika-programmirovaniya-stankov-s-chpu-na-naibolee-polnom-poligone-vspomogatelnyh-g-funkciy.html) на 29 странице есть интересный график.
