### ISSUE TITLE
Возможно ли с данной библиотекой контролировать процесс разгона?

### ISSUE THREAD

**Issue by Denis20221** [GyverLibs/GyverStepper#9]
К примеру за 100 шагов плавно изменить паузу между шагами от 1000мкс до 100мкс?

**Comment by GyverLibs** [comment]
Библиотека позволяет:
- Двигать мотор на указанную позицию с настройкой скорости и ускорения (трапецеидальный профиль скорости)
- Плавно управлять скоростью мотора без привязки к координате

**Comment by Denis20221** [comment]
Прошу прощения, может я плохо смотрел или плохо понял. Но интересует именно возможность жестко контролировать процесс разгона\торможения. Вот приказать что бы именно сделал 100 шагов(не больше и не меньше) и в течении этих шагов произошел плавный разгон или торможение с указанными скоростями. Не могли бы вы привести простой пример? Я не увидел именно подобного, может плохо смотрел. Заранее спасибо!

**Comment by GyverLibs** [comment]
Именно это и делает библиотека, см. любой пример. Параметры движения настраиваются, затем при помощи setTarget мотору задаётся цель в шагах

**Comment by Denis20221** [comment]
Спасибо за ответ!
